### PR TITLE
API routes 

### PR DESCRIPTION
**Pull request by katebrune**
- added in new routes
- got rid of old unnecessary ones
- based off of the architecture diagram on the drive

### CODE REVIEW

**Comment by katebrune** [comment]
ignore Alerts.py file, started that and then started work on the api

**Comment by katebrune** [comment]
jk finished writing the alert function

**Review by rgoluch — APPROVED** [review]
Looks good with the cleaning up and adding in the new routes. Have the routes been tested?

**Comment by katebrune** [comment]
ya i tested them with postman, wanna eventually try to figure out how to test them with unit tests

**Comment by gould-ann** [comment]
> ya i tested them with postman, wanna eventually try to figure out how to test them with unit tests

look at api_tests.py

**Pull request merged**
